version: '3'
services:
    # service a
    a:
        container_name: service_a
        build: ./service_a
        volumes:
            - ./service_a:/app
        depends_on:
            mq:
                condition: service_healthy
        ports:
            - 5000:5000
        restart: always

    # service b
    b:
        container_name: service_b
        build: ./service_b
        volumes:
            - ./service_b:/app
        depends_on:
            mq:
                condition: service_healthy
        ports:
            - 5001:5001
        restart: always

    # event bus
    mq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./rabbitmq_data:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 10s
            retries: 3

    